services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - test-vol:/usr/local/pgsql/data

volumes:
  test-vol:
    external: true
